title: Bookworm
description: Публикации о технологиях, ИИ и цифровых продуктах.
theme: minima
lang: ru
markdown: kramdown
url: "https://antonkoshuba.github.io"
baseurl: "/bookworm"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
